name: "Nodejs App CICD pipeline"

on: 
    push: 
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

      paths-ignore:
             -  'README.md'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"            
      - name: Install dependencies
        run: npm install

      - name: Test app
        run: echo "npm test"

      - name: Build
        run: echo " building application " 

      - name: Run ESLint
        run: echo " ESLint succesful " 

    
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: docnjila/sample-nodes
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
      
# full deployment
            
